In [7]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata
from passwords import *

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.ny.gov", API_TOKEN)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.ny.gov,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("wujg-7c2s", limit=500000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [8]:
results_df

,transit_timestamp,transit_mode,station_complex_id,station_complex,borough,payment_method,fare_class_category,ridership,transfers,latitude,longitude,georeference,:@computed_region_kjdx_g34t,:@computed_region_yamh_8v7k,:@computed_region_wbg7_3whc
0,2022-08-15T07:00:00.000,subway,151,"145 St (A,C,B,D)",Manhattan,metrocard,Metrocard - Seniors & Disability,17.0,1.0,40.824783,-73.944214,"{'type': 'Point', 'coordinates': [-73.944214, ...",2095,749,758
1,2022-08-15T10:00:00.000,subway,69,25 Av (D),Brooklyn,omny,OMNY - Full Fare,26.0,1.0,40.597706,-73.98683,"{'type': 'Point', 'coordinates': [-73.98683, 4...",2090,894,892
2,2022-08-15T06:00:00.000,subway,187,Shepherd Av (C),Brooklyn,metrocard,Metrocard - Fair Fare,11.0,0.0,40.67413,-73.88075,"{'type': 'Point', 'coordinates': [-73.88075, 4...",2137,894,886
3,2022-08-15T06:00:00.000,subway,127,DeKalb Av (L),Brooklyn,metrocard,Metrocard - Seniors & Disability,8.0,1.0,40.70381,-73.91843,"{'type': 'Point', 'coordinates': [-73.91843, 4...",2090,894,820
4,2022-08-05T16:00:00.000,subway,72,Fort Hamilton Pkwy (N),Brooklyn,metrocard,Metrocard - Unlimited 30-Day,23.0,0.0,40.631386,-74.00535,"{'type': 'Point', 'coordinates': [-74.00535, 4...",2090,894,897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2022-05-02T09:00:00.000,subway,34,53 St (R),Brooklyn,metrocard,Metrocard - Full Fare,114.0,1.0,40.64507,-74.01403,"{'type': 'Point', 'coordinates': [-74.01403, 4...",2090,894,899
499996,2022-05-02T21:00:00.000,subway,109,Fresh Pond Rd (M),Queens,metrocard,Metrocard - Unlimited 7-Day,10.0,0.0,40.706184,-73.895874,"{'type': 'Point', 'coordinates': [-73.895874, ...",2137,196,849
499997,2022-05-02T14:00:00.000,subway,103,"Bowery (J,Z)",Manhattan,metrocard,Metrocard - Unlimited 7-Day,19.0,0.0,40.72028,-73.99391,"{'type': 'Point', 'coordinates': [-73.99391, 4...",2095,749,718
499998,2022-05-02T17:00:00.000,subway,471,34 St-Hudson Yards (7),Manhattan,metrocard,Metrocard - Unlimited 30-Day,154.0,0.0,40.755882,-74.00191,"{'type': 'Point', 'coordinates': [-74.00191, 4...",2095,749,717
499999,2022-05-02T08:00:00.000,subway,262,"67 Av (M,R)",Queens,metrocard,Metrocard - Seniors & Disability,47.0,0.0,40.726524,-73.85272,"{'type': 'Point', 'coordinates': [-73.85272, 4...",2137,196,845

In [9]:
results_df["station_complex"]

0               145 St (A,C,B,D)
1                      25 Av (D)
2                Shepherd Av (C)
3                  DeKalb Av (L)
4         Fort Hamilton Pkwy (N)
                   ...
499995                 53 St (R)
499996         Fresh Pond Rd (M)
499997              Bowery (J,Z)
499998    34 St-Hudson Yards (7)
499999               67 Av (M,R)
Name: station_complex, Length: 500000, dtype: object

In [10]:
filtered_df = results_df[results_df['station_complex'] == 'Bedford Park Blvd-Lehman College (4)']

# Select the required columns
selected_columns = ['transit_mode', 'station_complex', 'payment_method', 'fare_class_category']
filtered_df = filtered_df[selected_columns]

# Display the filtered table
filtered_df

,transit_mode,station_complex,payment_method,fare_class_category
11117,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Other
11202,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Full Fare
11224,subway,Bedford Park Blvd-Lehman College (4),omny,OMNY - Full Fare
11505,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Fair Fare
11909,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Full Fare
...,...,...,...,...
442880,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Unlimited 7-Day
442918,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Students
442964,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Other
443058,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Full Fare
443113,subway,Bedford Park Blvd-Lehman College (4),metrocard,Metrocard - Full Fare